services:
  api:
    build: .
    container_name: live-translate-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FLASK_DEBUG=False
      - HF_TOKEN=${HF_TOKEN}
      - TRANSFORMERS_CACHE=/models
      - HF_HOME=/models
    volumes:
      - huggingface-models:/models
      - ./recordings:/app/recordings  # Mount recordings directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G

volumes:
  huggingface-models:
    driver: local
