version: '3.8'

services:
  api:
    build: .
    container_name: live-translate-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
